version: '3.8'

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: socialmedia
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/socialmedia
    env_file:
      - .env
    ports:
      - '3000:3000'
    command: >
      sh -c "npm run migrate -- deploy && npm start"
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data:
