openapi: 3.0.0
info:
  version: 1.0.0
  title: Social Media API Documentation
  description: Social Media API Documentation
  contact:
    email: mohamed.sheriif.elsayed@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://localhost:3000/api/v1
paths:
  $ref: ./paths/index.yaml
components:
  $ref: ./components/index.yaml

security:
  - bearerAuth: []
